config/routes.rb
Rails.application.routes.draw do
  namespace :account do
    resources :projects do
        resources :tasks
    end
  end
  root 'dashboard#index'
  get 'hello_world', to: 'hello_world#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :title, :description, presence: true

  self.per_page = 8
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :title, :description, :deadline, presence: true

  def self.for_project(project_id)
    where(project_id: project_id)
  end
end

app/controllers/account/projects_controller.rb
class Account::ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.all.paginate(page: params[:page], per_page: 8)

  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to account_projects_path
    else
      flash[:danger] = 'Something went wrong, please try again'
      render :new
    end
  end

  def show
    @tasks = @project.tasks
  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      flash[:success] = 'Project updated!'
      redirect_to account_project_path
    else
      flash[:danger] = 'Something went wrong, please try again'
      render :edit
    end
  end

  def destroy
    if @project.destroy
      flash[:success] = 'Project deleted!'
      redirect_to account_projects_path
    else
      flash[:danger] = 'Something went wrong, please try again'
      render :destroy
    end
  end

  private
  def project_params
    params.require(:project).permit!
  end
  def set_project
    @project = Project.find(params[:id])
  end

end

app/controllers/account/tasks_controller.rb
class Account::TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.for_project(params[:project_id])

  end

  def new
    @task = Task.new
  end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new(task_params)
    if @task.save
      redirect_to account_project_path(@project)
    else
      flash[:danger] = 'Something went wrong, please try again'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update_attributes(task_params)
      flash[:success] = 'Task updated!'
      redirect_to account_project_tasks_path
    else
      flash[:danger] = 'Something went wrong, please try again'
      render :edit
    end
  end

  def destroy
    if @task.delete
      flash[:success] = 'Task deleted!'
      redirect_to account_project_tasks_path
    else
      flash[:danger] = 'Something went wrong, please try again'
      render :destroy
    end
  end

  private
  def task_params
    params.require(:task).permit!
  end
  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/helpers/account/projects_helper.rb
module Account::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<section class="hero is-fullheight">
  <div class="hero-body">
    <div class="container">
      <h1 class="title center">
        I'm ready to manage your projects!
      </h1>
      <p class="subtitle center">
        Inspired by Asana
      </p>
      <figure class="center">
        <img src="https://app.asana.com/-/static/apps/asana/view/reskin_logo.png">
      </figure>
    
      <p class="center"><%=link_to 'Projects', account_projects_path, class: 'button is-small'%></p>
    </div>
  </div>
</section>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%flash.each do |name, message|%>
      <div class="notification is-<%=name%>">
        <button class="delete" onclick="parentNode.remove()"></button>
        <%= message%>
      </div>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_form_for_project.html.erb
<div class="field is-grouped is-grouped-centered">
  <div class="control">
    <%= form_for [:account, @project] do |form| %>
      <%=form.label :title %>
      <%=form.text_field :title, class:'input is-primary', placeholder: 'Title' %>
      <%=form.label :description %>
      <%=form.text_field :description, class:'input is-primary', placeholder: 'Description'  %>
      <%= form.submit 'Submit', class:'button is-primary is-outlined' %>
    <%end%>
  </div>
</div>

app/views/partials/_form_for_task.html.erb
<div class="field is-grouped is-grouped-centered">
  <div class="control">
    <%= form_for [:account, :project, @task] do |form| %>
  <%=form.label :title %>
  <%=form.text_field :title, class:'input is-primary', placeholder: 'Title' %>
  <%=form.label :description %>
  <%=form.text_field :description, class:'input is-primary', placeholder: 'Description'  %>
  <%=form.label :deadline %>
  <%=form.date_field :deadline, class:'input is-primary', placeholder: 'Deadline' %>
  <%= form.submit 'Submit', class:'button is-primary is-outlined' %>
    <%end%>
  </div>
</div>

app/views/partials/_show_project.html.erb
  <div class="column is-one-quarter">
    <p class="title"><%=link_to project.title, account_project_path(project.id)%></p>
    <p class="subtitle"><%=project.description%></p>
    <p>There are <%=project.tasks.count%> tasks</p>
    <p> <%=link_to 'Add new task', new_account_project_task_path(project.id)%></p>
    <%=link_to 'Edit', edit_account_project_path(project.id) %>
    <%=link_to 'Delete', account_project_path(project.id), method: :delete %>
  </div>

app/views/partials/_show_task.html.erb
<div class="column is-one-quarter box">
  <p class="title"><%=task.title%></p>
  <p class="subtitle"><%=task.description%></p>
  <p>Created: <%=task.created_at.to_date%></p>
  <p>Deadline:<%=task.deadline%></p>
  <%=link_to 'Edit', edit_account_project_task_path(task.project_id, task.id) %>
  <%=link_to 'Delete', account_project_task_path(task.project_id, task.id), method: :delete %>
</div>